ASSIGNMENT - 1

In [1]:
#install the libraries
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#import the libraries
import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to C:\Users\Rajeshwari G
[nltk_data]     L\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Rajeshwari G
[nltk_data]     L\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Rajeshwari G
[nltk_data]     L\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Rajeshwari G
[nltk_data]     L\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [3]:
#input two paragraphs
text = """Natural Language Processing (NLP) is a field of Artificial Intelligence. 
         It helps computers understand, interpret and generate human language. 
         Many applications, such as: chatbots, translation systems, and voice assistants use NLP techniques.

         Data preprocessing is an important step in NLP. Raw text often contains punctuation marks, 
         stop words, and unnecessary symbols. Cleaning the text improves the performance of machine learning models; 
         therefore, preprocessing is essential."""

In [4]:
words = word_tokenize(text)
print("Tokenized Words:\n", words)

Tokenized Words:
 ['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'field', 'of', 'Artificial', 'Intelligence', '.', 'It', 'helps', 'computers', 'understand', ',', 'interpret', 'and', 'generate', 'human', 'language', '.', 'Many', 'applications', ',', 'such', 'as', ':', 'chatbots', ',', 'translation', 'systems', ',', 'and', 'voice', 'assistants', 'use', 'NLP', 'techniques', '.', 'Data', 'preprocessing', 'is', 'an', 'important', 'step', 'in', 'NLP', '.', 'Raw', 'text', 'often', 'contains', 'punctuation', 'marks', ',', 'stop', 'words', ',', 'and', 'unnecessary', 'symbols', '.', 'Cleaning', 'the', 'text', 'improves', 'the', 'performance', 'of', 'machine', 'learning', 'models', ';', 'therefore', ',', 'preprocessing', 'is', 'essential', '.']


In [5]:
#Removing Punctuation Marks
words_no_punc = [word for word in words if word not in string.punctuation]
print("\nAfter Removing Punctuation:\n", words_no_punc)


After Removing Punctuation:
 ['Natural', 'Language', 'Processing', 'NLP', 'is', 'a', 'field', 'of', 'Artificial', 'Intelligence', 'It', 'helps', 'computers', 'understand', 'interpret', 'and', 'generate', 'human', 'language', 'Many', 'applications', 'such', 'as', 'chatbots', 'translation', 'systems', 'and', 'voice', 'assistants', 'use', 'NLP', 'techniques', 'Data', 'preprocessing', 'is', 'an', 'important', 'step', 'in', 'NLP', 'Raw', 'text', 'often', 'contains', 'punctuation', 'marks', 'stop', 'words', 'and', 'unnecessary', 'symbols', 'Cleaning', 'the', 'text', 'improves', 'the', 'performance', 'of', 'machine', 'learning', 'models', 'therefore', 'preprocessing', 'is', 'essential']


In [6]:
#Stop Word Removal
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words_no_punc if word.lower() not in stop_words]
print("\nAfter Stopword Removal:\n", filtered_words)


After Stopword Removal:
 ['Natural', 'Language', 'Processing', 'NLP', 'field', 'Artificial', 'Intelligence', 'helps', 'computers', 'understand', 'interpret', 'generate', 'human', 'language', 'Many', 'applications', 'chatbots', 'translation', 'systems', 'voice', 'assistants', 'use', 'NLP', 'techniques', 'Data', 'preprocessing', 'important', 'step', 'NLP', 'Raw', 'text', 'often', 'contains', 'punctuation', 'marks', 'stop', 'words', 'unnecessary', 'symbols', 'Cleaning', 'text', 'improves', 'performance', 'machine', 'learning', 'models', 'therefore', 'preprocessing', 'essential']


In [7]:
#Stemming
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_words]
print("\nAfter Stemming:\n", stemmed_words)


After Stemming:
 ['natur', 'languag', 'process', 'nlp', 'field', 'artifici', 'intellig', 'help', 'comput', 'understand', 'interpret', 'gener', 'human', 'languag', 'mani', 'applic', 'chatbot', 'translat', 'system', 'voic', 'assist', 'use', 'nlp', 'techniqu', 'data', 'preprocess', 'import', 'step', 'nlp', 'raw', 'text', 'often', 'contain', 'punctuat', 'mark', 'stop', 'word', 'unnecessari', 'symbol', 'clean', 'text', 'improv', 'perform', 'machin', 'learn', 'model', 'therefor', 'preprocess', 'essenti']


In [8]:
#Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
print("\nAfter Lemmatization:\n", lemmatized_words)


After Lemmatization:
 ['Natural', 'Language', 'Processing', 'NLP', 'field', 'Artificial', 'Intelligence', 'help', 'computer', 'understand', 'interpret', 'generate', 'human', 'language', 'Many', 'application', 'chatbots', 'translation', 'system', 'voice', 'assistant', 'use', 'NLP', 'technique', 'Data', 'preprocessing', 'important', 'step', 'NLP', 'Raw', 'text', 'often', 'contains', 'punctuation', 'mark', 'stop', 'word', 'unnecessary', 'symbol', 'Cleaning', 'text', 'improves', 'performance', 'machine', 'learning', 'model', 'therefore', 'preprocessing', 'essential']


ASSIGNMENT - 2

In [9]:
#input text
documents = [
    "Natural language processing is very interesting domain", 
    "Machine learning and natural language processing are related", 
    "I enjoy learning both NLP and machine learning"
]

In [10]:
#Bags of Words(BoW)
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
X_bow = bow.fit_transform(documents)

print("Feature Names:\n", bow.get_feature_names_out())
print("\nBoW Matrix:\n", X_bow.toarray())

Feature Names:
 ['and' 'are' 'both' 'domain' 'enjoy' 'interesting' 'is' 'language'
 'learning' 'machine' 'natural' 'nlp' 'processing' 'related' 'very']

BoW Matrix:
 [[0 0 0 1 0 1 1 1 0 0 1 0 1 0 1]
 [1 1 0 0 0 0 0 1 1 1 1 0 1 1 0]
 [1 0 1 0 1 0 0 0 2 1 0 1 0 0 0]]


In [11]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(documents)

print("Feature Names:\n", tfidf.get_feature_names_out())
print("\nTF-IDF Matrix:\n", X_tfidf.toarray())

Feature Names:
 ['and' 'are' 'both' 'domain' 'enjoy' 'interesting' 'is' 'language'
 'learning' 'machine' 'natural' 'nlp' 'processing' 'related' 'very']

TF-IDF Matrix:
 [[0.         0.         0.         0.41756662 0.         0.41756662
  0.41756662 0.31757018 0.         0.         0.31757018 0.
  0.31757018 0.         0.41756662]
 [0.32516555 0.42755362 0.         0.         0.         0.
  0.         0.32516555 0.32516555 0.32516555 0.32516555 0.
  0.32516555 0.42755362 0.        ]
 [0.29898437 0.         0.39312851 0.         0.39312851 0.
  0.         0.         0.59796874 0.29898437 0.         0.39312851
  0.         0.         0.        ]]


In [12]:
text1 = """Artificial intelligence is rapidly transforming the world. Machine learning is a core part of AI
that allows systems to learn from data and improve over time. Deep learning, a subset of machine learning,
uses neural networks with multiple layers to model complex patterns. Natural language processing enables
machines to understand and generate human language. Applications include chatbots, translation systems,
and sentiment analysis. Data plays a crucial role in training machine learning models. High-quality data
helps improve the accuracy and performance of these models. Python is widely used in AI due to its rich
ecosystem of libraries such as numpy, pandas, scikit-learn, and tensorflow. Supervised learning involves
training a model on labeled data, while unsupervised learning finds patterns in unlabeled data.
Reinforcement learning focuses on decision-making by rewarding desired actions. AI is used in healthcare,
finance, education, and many other industries. As technology advances, ethical considerations in AI
become increasingly important. Responsible AI ensures fairness, transparency, and accountability."""

In [13]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
from gensim.models import Word2Vec
model = Word2Vec(processed_sentences, vector_size=100,window=8, min_count=1, workers=4, epochs=100)

In [17]:
print(model.wv.key_to_index)

{'learning': 0, 'ai': 1, 'data': 2, 'machine': 3, 'systems': 4, 'language': 5, 'improve': 6, 'used': 7, 'patterns': 8, 'model': 9, 'models': 10, 'training': 11, 'include': 12, 'applications': 13, 'chatbots': 14, 'translation': 15, 'sentiment': 16, 'human': 17, 'generate': 18, 'understand': 19, 'machines': 20, 'enables': 21, 'processing': 22, 'natural': 23, 'accountability': 24, 'multiple': 25, 'complex': 26, 'layers': 27, 'intelligence': 28, 'rapidly': 29, 'transforming': 30, 'world': 31, 'core': 32, 'part': 33, 'allows': 34, 'learn': 35, 'time': 36, 'deep': 37, 'subset': 38, 'uses': 39, 'neural': 40, 'networks': 41, 'plays': 42, 'analysis': 43, 'role': 44, 'crucial': 45, 'focuses': 46, 'desired': 47, 'actions': 48, 'healthcare': 49, 'finance': 50, 'education': 51, 'many': 52, 'industries': 53, 'technology': 54, 'advances': 55, 'ethical': 56, 'considerations': 57, 'become': 58, 'increasingly': 59, 'important': 60, 'responsible': 61, 'ensures': 62, 'fairness': 63, 'rewarding': 64, 'rein

In [18]:
from gensim.utils import simple_preprocess

# Convert to tokens
tokens = simple_preprocess(text)

# Word2Vec
sentences = [tokens]

In [19]:
from gensim.models import Word2Vec

model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

In [22]:
print(list(model.wv.key_to_index.keys()))

['and', 'nlp', 'is', 'the', 'preprocessing', 'text', 'of', 'language', 'chatbots', 'translation', 'as', 'such', 'applications', 'many', 'human', 'generate', 'essential', 'understand', 'interpret', 'voice', 'computers', 'helps', 'it', 'intelligence', 'artificial', 'field', 'processing', 'systems', 'use', 'assistants', 'therefore', 'models', 'learning', 'machine', 'performance', 'improves', 'cleaning', 'symbols', 'unnecessary', 'words', 'stop', 'marks', 'punctuation', 'contains', 'often', 'raw', 'in', 'step', 'important', 'an', 'data', 'techniques', 'natural']


In [29]:
tokens = ["artificial", "intelligence", "machine", "learning", "data", "models", ...]

for w in ['machine', 'learning', 'data', 'model', 'ai', 'intelligence']:
    if w in model.wv:
        print(f"{w} exists")
    else:
        print(f"{w} NOT in vocabulary")

machine exists
learning exists
data exists
model NOT in vocabulary
ai NOT in vocabulary
intelligence exists


In [27]:
words_to_check = ['machine', 'learning', 'data', 'artificial', 'intelligence']
print("Similarity between 'machine' and 'learning':",
      model.wv.similarity('machine', 'learning'))

print("Similarity between 'data' and 'artificial':",
      model.wv.similarity('data', 'artificial'))

Similarity between 'machine' and 'learning': 0.14919457
Similarity between 'data' and 'artificial': 0.15747464


In [28]:
print("\nWords similar to 'learning':")
print(model.wv.most_similar('learning'))


Words similar to 'learning':
[('applications', 0.23786135017871857), ('techniques', 0.22459599375724792), ('contains', 0.19815020263195038), ('interpret', 0.15732790529727936), ('such', 0.15729406476020813), ('machine', 0.14919456839561462), ('improves', 0.14482620358467102), ('symbols', 0.13172423839569092), ('punctuation', 0.12315240502357483), ('and', 0.10864108800888062)]


ASSIGNMENT-3

In [13]:
#Feather Engineering
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    "Natural language processing is very interesting domain", 
    "Machine learning and natural language processing are related", 
    "I enjoy learning both NLP and machine learning"
]

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus)

print(X_tfidf.toarray())
print(tfidf.get_feature_names_out())

[[0.         0.         0.         0.41756662 0.         0.41756662
  0.41756662 0.31757018 0.         0.         0.31757018 0.
  0.31757018 0.         0.41756662]
 [0.32516555 0.42755362 0.         0.         0.         0.
  0.         0.32516555 0.32516555 0.32516555 0.32516555 0.
  0.32516555 0.42755362 0.        ]
 [0.29898437 0.         0.39312851 0.         0.39312851 0.
  0.         0.         0.59796874 0.29898437 0.         0.39312851
  0.         0.         0.        ]]
['and' 'are' 'both' 'domain' 'enjoy' 'interesting' 'is' 'language'
 'learning' 'machine' 'natural' 'nlp' 'processing' 'related' 'very']


In [15]:
#Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
sentences = [
    "Natural language processing is very interesting domain", 
    "Machine learning and natural language processing are related", 
    "I enjoy learning both NLP and machine learning"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

similarlity = cosine_similarity(X)
print(similarlity)

[[1.         0.30978865 0.        ]
 [0.30978865 1.         0.38887766]
 [0.         0.38887766 1.        ]]


In [86]:
#Supervised Learning
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
texts = [
    "How long will this internship last",
    "It's already been three months",
    "I'm just curious",
    "What about the projects and stipend too",
    "I didn't get any mail",
    "I still didn't get the webinar certificate",
    "The host lied telling we'll get the certificate",
    "I mailed her personally yet no response",
    "Will I get a response?",
    "Or was it just another lie"
]

labels = [1,1,1,1,1,0,0,0,0,0]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

X_train, X_test, y_train, y_test = train_test_split(X, labels, stratify=labels, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("y_train:", y_train)
print("y_test:", y_test)

Accuracy: 0.5
y_train: [1, 0, 0, 0, 1, 1, 1, 0]
y_test: [0, 1]


In [84]:
#Unsupervised Learning
from sklearn.cluster import KMeans
texts = [
    "How long will this internship last",
    "It's already been three months",
    "I'm just curious",
    "What about the projects and stipend too"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X)

print(kmeans.labels_)

print("UNSUPERVISED CLUSTERING - K-Means")

for text_item, label in zip(texts, kmeans.labels_):
    print(f"Cluster {label}: {text_item}")
    
print("\nCluster Centers Shape:")
print(kmeans.cluster_centers_.shape)
print("FINAL ASSIGNMENT COMPLETED SUCCESSFULLY")


[1 0 1 1]
UNSUPERVISED CLUSTERING - K-Means
Cluster 1: How long will this internship last
Cluster 0: It's already been three months
Cluster 1: I'm just curious
Cluster 1: What about the projects and stipend too

Cluster Centers Shape:
(2, 20)
FINAL ASSIGNMENT COMPLETED SUCCESSFULLY


In [85]:
print(X_train.shape)
print(X_test.shape)

(8, 42)
(2, 42)
